### ISSUE TITLE
bug: os platform detection no longer works

### ISSUE THREAD

**Issue by setchy** [gitify-app/website#201]
OS detection no longer working to render the correct download links

https://github.com/gitify-app/website/blob/92a357d780a2258525bf8da6b2b6a9ebbeb065be/src/components/LatestRelease.astro#L52 is always returning window as undefined and defaulting to macOS download link.

![Screenshot 2024-08-19 at 8 49 30 AM](https://github.com/user-attachments/assets/0613a1c9-e090-4bfb-a147-517a71166bc4)

This logic needs to run client-side, not server-side

**Comment by afonsojramos** [comment]
To solve our age old issue of fetching the latest release and knowing the client's OS what we could probably do is an Netlify Edge Function that is heavily cached.

https://docs.netlify.com/frameworks/astro/#edge-functions-examples
https://docs.netlify.com/edge-functions/optional-configuration/#response-caching

**Comment by afonsojramos** [comment]
In the past I've tried to ship SolidJS in the client (probably in some closed PR somewhere), but the waterfall of requests just delays everything..
